# Generated by Django 3.2 on 2021-12-12 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('tv_show', 'ТВ шоу')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='filmworkperson',
            name='role',
            field=models.CharField(blank=True, choices=[('actor', 'Актёр'), ('writer', 'Сценарист'), ('director', 'Режисёр')], max_length=20, verbose_name='Роль'),
        ),
    ]
