version: '3'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - movies_admin/.env
    networks:
      - test_net


  web:
    build: ./movies_admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movies_admin:/usr/src/movies_admin
    ports:
      - 8000:8000
    env_file:
      - movies_admin/.env
    depends_on:
      - db
    networks:
      - test_net

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - test_net

networks:
    test_net:
        driver: bridge